#!/usr/bin/env bash
set -euo pipefail

# Sync SDLC agents + Cursor rules to a local folder for easy sharing/onboarding.
#
# This does NOT magically create Cursor "Custom Agents" entries (Cursor UI still needs you to paste prompts),
# but it gives every developer the exact same prompt/rules files in a predictable location.
#
# Usage:
#   ./scripts/sync_cursor_assets.sh
#   ./scripts/sync_cursor_assets.sh --dest "$HOME/.cursor/sdlc"
#   ./scripts/sync_cursor_assets.sh --dest "/tmp/sdlc_cursor_assets" --force

DEST="${HOME}/.cursor/sdlc"
FORCE="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest)
      DEST="$2"
      shift 2
      ;;
    --force)
      FORCE="1"
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [--dest <path>] [--force]"
      exit 0
      ;;
    *)
      echo "Unknown arg: $1"
      exit 2
      ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "${DEST}"

copy_dir() {
  local src="$1"
  local dst="$2"
  if [[ ! -d "${src}" ]]; then
    echo "Missing dir: ${src}"
    exit 2
  fi
  mkdir -p "${dst}"
  if [[ "${FORCE}" == "1" ]]; then
    rsync -a --delete "${src}/" "${dst}/"
  else
    rsync -a "${src}/" "${dst}/"
  fi
}

copy_dir "${ROOT}/agents" "${DEST}/agents"
copy_dir "${ROOT}/.cursor/rules" "${DEST}/rules"
copy_dir "${ROOT}/schemas" "${DEST}/schemas"

cat > "${DEST}/SETUP.md" <<'EOF'
# SDLC Cursor Assets (Synced)

This folder is generated by `scripts/sync_cursor_assets.sh`.

## What’s inside
- `agents/`  : the SDLC agent prompts
- `rules/`   : Cursor rules (team-wide behavior)
- `schemas/` : JSON schemas for outputs

## How to use in Cursor
1) In Cursor, create Custom Agents by copying prompt text from `agents/<agent>.md`.
2) Ensure Cursor loads team rules from your repo `.cursor/rules/` (preferred), or reference `rules/sdlc_pipeline.md` as your behavior guide.
3) Use the repo scripts for persistence + validation:
   - `python3 scripts/new_run.py ...`
   - `python3 scripts/validate_run.py runs/...`
   - `python3 scripts/split_one_message_bundle.py ...`
EOF

echo "Synced to: ${DEST}"


